name: build

on: 
  push:
    paths-ignore:
      - 'documentation/**'
      - 'modelsrc/**'
      - 'appveyor.yml'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - 'modelsrc/**'
      - 'appveyor.yml'
      - 'README.md'

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android
        run: ./gradlew assembleDebug
        working-directory: android

      - name: Extract branch name
        shell: bash
        id: extract_branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: mv android/app/build/outputs/apk/debug/app-debug.apk android/app/build/outputs/apk/debug/xash-coop-android.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xash-coop-android
          path: android/app/build/outputs/apk/debug/xash-coop-android.apk

  definitions:
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
      gamedir: ${{ steps.extract_gamedir.outputs.gamedir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: mod_options.txt
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Extract gamedir
        shell: bash
        run: echo "gamedir=$(grep mod_options.txt -Ee 'GAMEDIR=[a-z]+' | cut -d '=' -f 2 | cut -d' ' -f 1)" >> $GITHUB_OUTPUT
        id: extract_gamedir

  build:
    runs-on: ${{ matrix.runs_on }}
    needs: [definitions]
    strategy:
      fail-fast: false
      matrix:
        platform: [linux-x86, windows-x86, windows-x64, linux-amd64, macos-x86_64, macos-arm64]
        include:
          - platform: linux-x86
            runs_on: ubuntu-latest
            cc: gcc
            cxx: g++
            os_suffix: linux
          - platform: windows-x86
            runs_on: windows-latest
            cc: cl
            cxx: cl
            os_suffix: windows
          - platform: windows-x64
            runs_on: windows-latest
            cc: cl
            cxx: cl
            os_suffix: windows64
          - platform: linux-amd64
            runs_on: ubuntu-24.04
            cc: gcc
            cxx: g++
            os_suffix: linux64
          - platform: macos-x86_64
            runs_on: macos-15
            cc: clang
            cxx: clang++
            os_suffix: macos-intel
          - platform: macos-arm64
            runs_on: macos-15
            cc: clang
            cxx: clang++
            os_suffix: macos-arm64
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      STEAMRT_SNAPSHOT: latest-steam-client-general-availability
      include_features: "false"
      fgd_name: "halflife_featureful.fgd"
      USE_VGUI: "OFF"
      vgui_suffix: "novgui"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checkout steam-runtime
      if: matrix.platform == 'linux-x86'
      uses: actions/checkout@v4
      with:
        repository: ValveSoftware/steam-runtime
        path: steam-runtime
    - name: Cache steam-runtime
      if: matrix.platform == 'linux-x86'
      id: cache-steam-runtime
      uses: actions/cache@v4
      with:
        path: com.valvesoftware.SteamRuntime.Sdk-i386-scout-sysroot.tar.gz
        key: steam-runtime-${{ env.STEAMRT_SNAPSHOT }}
    - name: Download steam-runtime
      if: matrix.platform == 'linux-x86' && steps.cache-steam-runtime.outputs.cache-hit != 'true'
      run: wget --no-verbose https://repo.steampowered.com/steamrt-images-scout/snapshots/${{ env.STEAMRT_SNAPSHOT }}/com.valvesoftware.SteamRuntime.Sdk-i386-scout-sysroot.tar.gz
    - name: Install steam runtime
      if: matrix.platform == 'linux-x86'
      run: |
        sudo apt update
        ./steam-runtime/setup_chroot.sh --i386 --tarball ./com.valvesoftware.SteamRuntime.Sdk-i386-scout-sysroot.tar.gz
        sudo sed -i 's/groups=sudo/groups=adm/g' /etc/schroot/chroot.d/steamrt_scout_i386.conf

    - name: Build on Linux x86 (Steam Runtime)
      if: matrix.platform == 'linux-x86'
      run: |
        schroot --chroot steamrt_scout_i386 -- cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DPOLLY=ON -B build -S . -DCMAKE_EXE_LINKER_FLAGS="-Wl,--no-undefined" -DUSE_VGUI=OFF -DCMAKE_INSTALL_PREFIX="$PWD/dist"
        schroot --chroot steamrt_scout_i386 -- cmake --build build --target all
        schroot --chroot steamrt_scout_i386 -- cmake --build build --target install

    - name: Install Native Linux Dependencies
      if: matrix.platform == 'linux-amd64'
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build build-essential libgl1-mesa-dev libglu1-mesa-dev

    - name: Build on Linux amd64
      if: matrix.platform == 'linux-amd64'
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DPOLLY=ON -D64BIT=ON -B build -S . -DUSE_VGUI=OFF -DCMAKE_INSTALL_PREFIX="$PWD/dist"
        cmake --build build --target all
        cmake --build build --target install

    - name: Install macOS Dependencies
      if: matrix.platform == 'macos-x86_64' || matrix.platform == 'macos-arm64'
      run: |
        brew install cmake ninja fontconfig

    - name: Build on macOS Intel (x86_64)
      if: matrix.platform == 'macos-x86_64'
      run: |
        cmake -G Ninja -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64" -DPOLLY=ON -DUSE_VGUI=OFF -DCMAKE_INSTALL_PREFIX="$PWD/dist"
        cmake --build build --target all
        cmake --build build --target install

    - name: Build on macOS Apple Silicon (arm64)
      if: matrix.platform == 'macos-arm64'
      run: |
        cmake -G Ninja -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64" -DPOLLY=ON -DUSE_VGUI=OFF -DCMAKE_INSTALL_PREFIX="$PWD/dist"
        cmake --build build --target all
        cmake --build build --target install

    - name: Set developer command prompt for Windows x86
      if: matrix.platform == 'windows-x86'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build on Windows x86
      if: matrix.platform == 'windows-x86'
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build -S . -DUSE_VGUI=OFF -DCMAKE_INSTALL_PREFIX="dist"
        cmake --build build --target all
        cmake --build build --target install

    - name: Set developer command prompt for Windows x64
      if: matrix.platform == 'windows-x64'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build on Windows x64
      if: matrix.platform == 'windows-x64'
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -D64BIT=ON -B build -S . -DUSE_VGUI=OFF -DCMAKE_INSTALL_PREFIX="dist"
        cmake --build build --target all
        cmake --build build --target install

    - name: Copy fgd to dist dir
      shell: bash
      run: mkdir -p dist/${{ needs.definitions.outputs.gamedir }} && cp fgd/halflife.fgd dist/${{ needs.definitions.outputs.gamedir }}/${{ env.fgd_name }} || true

    - name: Copy features to dist dir
      shell: bash
      if:  ${{ env.include_features == 'true' }}
      run: |
        cp -r features/ dist/${{ needs.definitions.outputs.gamedir }}/ || true
        if [ -d templates ]
        then
            cp -r templates/ dist/${{ needs.definitions.outputs.gamedir }}/ || true
        fi
        if [ -d sound ]
        then
            cp -r sound/ dist/${{ needs.definitions.outputs.gamedir }}/ || true
        fi
        if [ -d sprites ]
        then
            cp -r sprites/ dist/${{ needs.definitions.outputs.gamedir }}/ || true
        fi

    - name: Install Google Test
      if: matrix.platform == 'linux-x86'
      run: sudo apt -y install libgtest-dev

    - name: Run tests
      if: matrix.platform == 'linux-x86' && false
      working-directory: ./tests
      run: |
        cmake -GNinja -B build -S .
        cmake --build build --target all
        ./build/test

    - name: Upload platform artifact
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ needs.definitions.outputs.branch }}-${{ matrix.os_suffix }}-${{ env.vgui_suffix }}
        path: dist/${{ needs.definitions.outputs.gamedir }}

  release:
    if: false
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Fetch artifacts
        if: ${{ github.event_name == 'push' && !github.event.pull_request }}
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Remove old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        if: ${{ github.event_name == 'push' && !github.event.pull_request }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: continuous-${{ github.ref_name }}
          delete_release: true

      - name: Prepare release
        if: ${{ github.event_name == 'push' && !github.event.pull_request }}
        continue-on-error: true
        run: |
          cd artifacts/
          for i in hlsdk-*; do
            zip -r "$i" "$i"
            rm -rf "$i"
          done
          cd ..
          sleep 20s

      - name: Upload new release
        if: ${{ github.event_name == 'push' && !github.event.pull_request }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: artifacts/hlsdk-*.zip
          tag_name: continuous-${{ github.ref_name }}
          draft: false
          prerelease: true
          name: hlsdk-portable ${{ github.ref_name }} development build

  merge:
    runs-on: ubuntu-latest
    needs: [definitions, build]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: hlsdk-${{ needs.definitions.outputs.branch }}
          pattern: hlsdk-${{ needs.definitions.outputs.branch }}-*-novgui
          delete-merged: true
